/* ============================================================
   READMICAL 데이터 — 문장 / 단어
   ★ 콘텐츠는 이 파일만 고치면 됩니다. (편집법: 매뉴얼 참고)
   고친 뒤엔 sw.js 맨 위 VERSION 숫자를 +1 해서 커밋하세요.
   ============================================================ */
const DATA = {
  sentence:[
    { id:"5형식(1)", items:[
      {n:1, full:"사람들은 그 피해자를 영웅으로 여긴다", chunks:[{en:"People",ko:"사람들은",t:"subj"},{en:"find",ko:"여긴다",t:"verb"},{en:"the victim",ko:"그 피해자를",t:"obj"},{en:"a hero",ko:"영웅이라고",t:"comp"}]},
      {n:2, full:"우리는 그 엔진을 어둡게 칠한다", chunks:[{en:"We",ko:"우리는",t:"subj"},{en:"paint",ko:"칠한다",t:"verb"},{en:"the engine",ko:"그 엔진을",t:"obj"},{en:"dark",ko:"어둡게",t:"comp"}]},
      {n:3, full:"전문가들은 그 연구를 성공으로 여긴다", chunks:[{en:"Experts",ko:"전문가들은",t:"subj"},{en:"consider",ko:"여긴다",t:"verb"},{en:"the research",ko:"그 연구를",t:"obj"},{en:"a success",ko:"성공이라고",t:"comp"}]},
      {n:4, full:"그들은 그 문을 열어 둔다", chunks:[{en:"They",ko:"그들은",t:"subj"},{en:"leave",ko:"둔다",t:"verb"},{en:"the door",ko:"그 문을",t:"obj"},{en:"open",ko:"열린 채로",t:"comp"}]},
      {n:5, full:"사람들은 그 엔진을 따뜻하게 유지한다", chunks:[{en:"People",ko:"사람들은",t:"subj"},{en:"keep",ko:"유지한다",t:"verb"},{en:"the engine",ko:"그 엔진을",t:"obj"},{en:"warm",ko:"따뜻하게",t:"comp"}]},
      {n:6, full:"비평가들은 그 피해자를 영웅이라고 부른다", chunks:[{en:"Critics",ko:"비평가들은",t:"subj"},{en:"name",ko:"명명한다",t:"verb"},{en:"the victim",ko:"그 피해자를",t:"obj"},{en:"a hero",ko:"영웅이라고",t:"comp"}]},
      {n:7, full:"전문가들은 그 의견을 사실이라고 믿는다", chunks:[{en:"Experts",ko:"전문가들은",t:"subj"},{en:"believe",ko:"믿는다",t:"verb"},{en:"the opinion",ko:"그 의견을",t:"obj"},{en:"true",ko:"사실이라고",t:"comp"}]},
      {n:8, full:"구성원들은 그 부엌을 따뜻한 채로 둔다", chunks:[{en:"Members",ko:"구성원들은",t:"subj"},{en:"leave",ko:"둔다",t:"verb"},{en:"the kitchen",ko:"그 부엌을",t:"obj"},{en:"warm",ko:"따뜻한 채로",t:"comp"}]},
      {n:9, full:"사람들은 그 영화를 성공작이라고 부른다", chunks:[{en:"People",ko:"사람들은",t:"subj"},{en:"call",ko:"부른다",t:"verb"},{en:"the movie",ko:"그 영화를",t:"obj"},{en:"a success",ko:"성공이라고",t:"comp"}]},
      {n:10, full:"그 증거는 그 구성원이 정직함을 증명한다", chunks:[{en:"The evidence",ko:"그 증거는",t:"subj"},{en:"proves",ko:"증명한다",t:"verb"},{en:"the member",ko:"그 구성원이",t:"obj"},{en:"honest",ko:"정직하다고",t:"comp"}]},
      {n:11, full:"부모들은 그 구성원을 회장으로 선출한다", chunks:[{en:"Parents",ko:"부모들은",t:"subj"},{en:"elect",ko:"선출한다",t:"verb"},{en:"the member",ko:"그 구성원을",t:"obj"},{en:"president",ko:"회장으로",t:"comp"}]},
      {n:12, full:"우리는 그 부엌을 건조하게 유지한다", chunks:[{en:"We",ko:"우리는",t:"subj"},{en:"keep",ko:"유지한다",t:"verb"},{en:"the kitchen",ko:"그 부엌을",t:"obj"},{en:"dry",ko:"마른 채로",t:"comp"}]},
      {n:13, full:"성인들은 그 연구를 익숙하게 여긴다", chunks:[{en:"Adults",ko:"성인들은",t:"subj"},{en:"consider",ko:"여긴다",t:"verb"},{en:"the research",ko:"그 연구를",t:"obj"},{en:"familiar",ko:"익숙하다고",t:"comp"}]},
      {n:14, full:"사람들은 그 탁자를 빨갛게 칠한다", chunks:[{en:"People",ko:"사람들은",t:"subj"},{en:"paint",ko:"칠한다",t:"verb"},{en:"the table",ko:"그 탁자를",t:"obj"},{en:"red",ko:"빨갛게",t:"comp"}]},
      {n:15, full:"비평가들은 그 지도자를 영웅이라고 믿는다", chunks:[{en:"Critics",ko:"비평가들은",t:"subj"},{en:"believe",ko:"믿는다",t:"verb"},{en:"the leader",ko:"그 지도자를",t:"obj"},{en:"a hero",ko:"영웅이라고",t:"comp"}]},
      {n:16, full:"우리는 그 물을 따뜻한 채로 둔다", chunks:[{en:"We",ko:"우리는",t:"subj"},{en:"leave",ko:"둔다",t:"verb"},{en:"the water",ko:"그 물을",t:"obj"},{en:"warm",ko:"따뜻한 채로",t:"comp"}]},
      {n:17, full:"시민들은 그 구성원을 지도자로 선출한다", chunks:[{en:"Citizens",ko:"시민들은",t:"subj"},{en:"elect",ko:"선출한다",t:"verb"},{en:"the member",ko:"그 구성원을",t:"obj"},{en:"leader",ko:"지도자로",t:"comp"}]},
      {n:18, full:"사람들은 그 영화를 익숙하게 여긴다", chunks:[{en:"People",ko:"사람들은",t:"subj"},{en:"find",ko:"여긴다",t:"verb"},{en:"the movie",ko:"그 영화를",t:"obj"},{en:"familiar",ko:"익숙하다고",t:"comp"}]},
      {n:19, full:"의사들은 그 피해자가 지도자임을 증명한다", chunks:[{en:"Doctors",ko:"의사들은",t:"subj"},{en:"prove",ko:"증명한다",t:"verb"},{en:"the victim",ko:"그 피해자가",t:"obj"},{en:"a leader",ko:"지도자라고",t:"comp"}]},
      {n:20, full:"부모들은 그 영화를 이상하다고 여긴다", chunks:[{en:"Parents",ko:"부모들은",t:"subj"},{en:"consider",ko:"여긴다",t:"verb"},{en:"the movie",ko:"그 영화를",t:"obj"},{en:"strange",ko:"이상하다고",t:"comp"}]},
      {n:21, full:"우리는 이 수업을 Readmical이라고 부른다", chunks:[{en:"We",ko:"우리는",t:"subj"},{en:"call",ko:"부른다",t:"verb"},{en:"this class",ko:"이 수업을",t:"obj"},{en:"Readmical",ko:"Readmical이라고",t:"comp"}]},
      {n:22, full:"사람들은 그 구성원이 정직하다고 믿는다", chunks:[{en:"People",ko:"사람들은",t:"subj"},{en:"believe",ko:"믿는다",t:"verb"},{en:"the member",ko:"그 구성원이",t:"obj"},{en:"honest",ko:"정직하다고",t:"comp"}]},
      {n:23, full:"그 팀은 그 선수를 주장으로 선출한다", chunks:[{en:"The team",ko:"그 팀은",t:"subj"},{en:"elects",ko:"선출한다",t:"verb"},{en:"the athlete",ko:"그 선수를",t:"obj"},{en:"captain",ko:"주장으로",t:"comp"}]},
      {n:24, full:"성인들은 그 의견이 분명하다고 여긴다", chunks:[{en:"Adults",ko:"성인들은",t:"subj"},{en:"find",ko:"여긴다",t:"verb"},{en:"the opinion",ko:"그 의견이",t:"obj"},{en:"clear",ko:"분명하다고",t:"comp"}]},
      {n:25, full:"그들은 그 탁자를 빨갛게 칠한다", chunks:[{en:"They",ko:"그들은",t:"subj"},{en:"paint",ko:"칠한다",t:"verb"},{en:"the table",ko:"그 탁자를",t:"obj"},{en:"red",ko:"빨갛게",t:"comp"}]},
      {n:26, full:"전문가들은 그 스타를 전설이라고 부른다", chunks:[{en:"Experts",ko:"전문가들은",t:"subj"},{en:"name",ko:"명명한다",t:"verb"},{en:"the star",ko:"그 스타를",t:"obj"},{en:"a legend",ko:"전설이라고",t:"comp"}]},
      {n:27, full:"우리는 그 물을 따뜻하게 유지한다", chunks:[{en:"We",ko:"우리는",t:"subj"},{en:"keep",ko:"유지한다",t:"verb"},{en:"the water",ko:"그 물을",t:"obj"},{en:"warm",ko:"따뜻하게",t:"comp"}]},
      {n:28, full:"전문가들은 그 의견이 사실임을 증명한다", chunks:[{en:"Experts",ko:"전문가들은",t:"subj"},{en:"prove",ko:"증명한다",t:"verb"},{en:"the opinion",ko:"그 의견이",t:"obj"},{en:"true",ko:"사실이라고",t:"comp"}]},
      {n:29, full:"사람들은 그 지도자를 영웅이라고 부른다", chunks:[{en:"People",ko:"사람들은",t:"subj"},{en:"name",ko:"명명한다",t:"verb"},{en:"the leader",ko:"그 지도자를",t:"obj"},{en:"a hero",ko:"영웅이라고",t:"comp"}]},
      {n:30, full:"사람들은 그 스타를 전설이라고 부른다", chunks:[{en:"People",ko:"사람들은",t:"subj"},{en:"call",ko:"부른다",t:"verb"},{en:"the star",ko:"그 스타를",t:"obj"},{en:"a legend",ko:"전설이라고",t:"comp"}]},
    ]},
    { id:"5형식(2)", items:[
      {n:1, full:"", chunks:[{en:"Customers",ko:"고객들은",t:"subj"},{en:"have",ko:"시킨다",t:"verb"},{en:"the lady",ko:"그 숙녀를",t:"obj"},{en:"sit",ko:"앉게",t:"comp"},{en:"for an hour",ko:"한 시간 동안",t:"mod"}]},
      {n:2, full:"", chunks:[{en:"A citizen",ko:"한 시민이",t:"subj"},{en:"lets",ko:"둔다",t:"verb"},{en:"the crowd",ko:"그 군중을",t:"obj"},{en:"leave",ko:"떠나게",t:"comp"}]},
      {n:3, full:"", chunks:[{en:"A parent",ko:"한 부모가",t:"subj"},{en:"helps",ko:"돕는다",t:"verb"},{en:"the calm baby",ko:"그 차분한 아기가",t:"obj"},{en:"stand",ko:"서도록",t:"comp"}]},
      {n:4, full:"", chunks:[{en:"Parents",ko:"부모들은",t:"subj"},{en:"make",ko:"만든다",t:"verb"},{en:"the danger",ko:"그 위험을",t:"obj"},{en:"clear",ko:"분명하게",t:"comp"}]},
      {n:5, full:"", chunks:[{en:"A captain",ko:"한 주장이",t:"subj"},{en:"has",ko:"시킨다",t:"verb"},{en:"the team",ko:"그 팀을",t:"obj"},{en:"start",ko:"시작하게",t:"comp"}]},
      {n:6, full:"", chunks:[{en:"Doctors",ko:"의사들은",t:"subj"},{en:"let",ko:"둔다",t:"verb"},{en:"the patient",ko:"그 환자를",t:"obj"},{en:"sleep",ko:"자게",t:"comp"}]},
      {n:7, full:"", chunks:[{en:"A parent",ko:"한 부모가",t:"subj"},{en:"makes",ko:"만든다",t:"verb"},{en:"the baby",ko:"그 아기를",t:"obj"},{en:"laugh",ko:"웃게",t:"comp"},{en:"in the park",ko:"공원에서",t:"mod"}]},
      {n:8, full:"", chunks:[{en:"People",ko:"사람들은",t:"subj"},{en:"help",ko:"돕는다",t:"verb"},{en:"the group",ko:"그 집단이",t:"obj"},{en:"to succeed",ko:"성공하도록",t:"comp"}]},
      {n:9, full:"", chunks:[{en:"Families",ko:"가족들은",t:"subj"},{en:"have",ko:"시킨다",t:"verb"},{en:"the glass",ko:"그 유리잔을",t:"obj"},{en:"cleaned",ko:"닦이게",t:"comp"},{en:"in the kitchen",ko:"부엌에서",t:"mod"}]},
      {n:10, full:"", chunks:[{en:"A parent",ko:"한 부모가",t:"subj"},{en:"lets",ko:"둔다",t:"verb"},{en:"the calm baby",ko:"그 차분한 아기를",t:"obj"},{en:"sleep",ko:"자게",t:"comp"}]},
      {n:11, full:"", chunks:[{en:"An expert",ko:"한 전문가가",t:"subj"},{en:"gets",ko:"시킨다",t:"verb"},{en:"the floor",ko:"그 바닥을",t:"obj"},{en:"cleaned",ko:"닦이게",t:"comp"}]},
      {n:12, full:"", chunks:[{en:"A member",ko:"한 구성원이",t:"subj"},{en:"makes",ko:"만든다",t:"verb"},{en:"the project",ko:"그 프로젝트를",t:"obj"},{en:"a success",ko:"성공으로",t:"comp"}]},
      {n:13, full:"", chunks:[{en:"Families",ko:"가족들은",t:"subj"},{en:"have",ko:"시킨다",t:"verb"},{en:"the floor",ko:"그 바닥을",t:"obj"},{en:"washed",ko:"닦이게",t:"comp"},{en:"in the kitchen",ko:"부엌에서",t:"mod"}]},
      {n:14, full:"", chunks:[{en:"A critic",ko:"한 비평가가",t:"subj"},{en:"gets",ko:"만든다",t:"verb"},{en:"the music",ko:"그 음악을",t:"obj"},{en:"playing",ko:"흘러나오게",t:"comp"},{en:"in the car",ko:"차 안에서",t:"mod"}]},
      {n:15, full:"", chunks:[{en:"Experts",ko:"전문가들은",t:"subj"},{en:"make",ko:"만든다",t:"verb"},{en:"the group",ko:"그 집단을",t:"obj"},{en:"agree",ko:"동의하게",t:"comp"},{en:"with them",ko:"그들에게",t:"mod"}]},
      {n:16, full:"", chunks:[{en:"A leader",ko:"한 지도자가",t:"subj"},{en:"has",ko:"시킨다",t:"verb"},{en:"the group",ko:"그 집단을",t:"obj"},{en:"decide",ko:"결정하게",t:"comp"}]},
      {n:17, full:"", chunks:[{en:"A doctor",ko:"한 의사가",t:"subj"},{en:"gets",ko:"시킨다",t:"verb"},{en:"the group",ko:"그 집단이",t:"obj"},{en:"to decide",ko:"결정하도록",t:"comp"}]},
      {n:18, full:"", chunks:[{en:"Doctors",ko:"의사들은",t:"subj"},{en:"help",ko:"돕는다",t:"verb"},{en:"people",ko:"사람들이",t:"obj"},{en:"understand",ko:"이해하도록",t:"comp"}]},
      {n:19, full:"", chunks:[{en:"Adults",ko:"성인들은",t:"subj"},{en:"let",ko:"둔다",t:"verb"},{en:"the child",ko:"그 아이를",t:"obj"},{en:"play",ko:"놀게",t:"comp"},{en:"on the beach",ko:"해변에서",t:"mod"}]},
      {n:20, full:"", chunks:[{en:"Doctors",ko:"의사들은",t:"subj"},{en:"make",ko:"만든다",t:"verb"},{en:"the issue",ko:"그 문제를",t:"obj"},{en:"understood",ko:"이해되게",t:"comp"}]},
      {n:21, full:"", chunks:[{en:"A member",ko:"한 구성원이",t:"subj"},{en:"lets",ko:"둔다",t:"verb"},{en:"the guest",ko:"그 손님을",t:"obj"},{en:"sit",ko:"앉게",t:"comp"},{en:"for a minute",ko:"잠시 동안",t:"mod"}]},
      {n:22, full:"", chunks:[{en:"A critic",ko:"한 비평가가",t:"subj"},{en:"helps",ko:"돕는다",t:"verb"},{en:"the class",ko:"그 학급이",t:"obj"},{en:"learn",ko:"배우도록",t:"comp"}]},
      {n:23, full:"", chunks:[{en:"Parents",ko:"부모들은",t:"subj"},{en:"get",ko:"시킨다",t:"verb"},{en:"the baby",ko:"그 아기가",t:"obj"},{en:"to sleep",ko:"자도록",t:"comp"},{en:"for an hour",ko:"한 시간 동안",t:"mod"}]},
      {n:24, full:"", chunks:[{en:"An adult",ko:"한 성인이",t:"subj"},{en:"helps",ko:"돕는다",t:"verb"},{en:"the child",ko:"그 아이가",t:"obj"},{en:"to succeed",ko:"성공하도록",t:"comp"}]},
      {n:25, full:"", chunks:[{en:"People",ko:"사람들은",t:"subj"},{en:"get",ko:"만든다",t:"verb"},{en:"the engine",ko:"그 엔진을",t:"obj"},{en:"running",ko:"작동하게",t:"comp"},{en:"on the highway",ko:"고속도로에서",t:"mod"}]},
      {n:26, full:"", chunks:[{en:"Members",ko:"구성원들은",t:"subj"},{en:"help",ko:"돕는다",t:"verb"},{en:"the proud team",ko:"그 자랑스러운 팀이",t:"obj"},{en:"to win",ko:"이기도록",t:"comp"}]},
      {n:27, full:"", chunks:[{en:"People",ko:"사람들은",t:"subj"},{en:"get",ko:"시킨다",t:"verb"},{en:"the glass",ko:"그 유리잔을",t:"obj"},{en:"fixed",ko:"고쳐지게",t:"comp"}]},
      {n:28, full:"", chunks:[{en:"A critic",ko:"한 비평가가",t:"subj"},{en:"makes",ko:"만든다",t:"verb"},{en:"the science",ko:"그 과학을",t:"obj"},{en:"understood",ko:"이해되게",t:"comp"}]},
      {n:29, full:"", chunks:[{en:"A doctor",ko:"한 의사가",t:"subj"},{en:"has",ko:"시킨다",t:"verb"},{en:"the old lady",ko:"그 나이 든 숙녀를",t:"obj"},{en:"wait",ko:"기다리게",t:"comp"}]},
      {n:30, full:"", chunks:[{en:"People",ko:"사람들은",t:"subj"},{en:"let",ko:"둔다",t:"verb"},{en:"the animal",ko:"그 동물을",t:"obj"},{en:"run",ko:"달리게",t:"comp"},{en:"in the desert",ko:"사막에서",t:"mod"}]},
      {n:31, full:"", chunks:[{en:"A critic",ko:"한 비평가가",t:"subj"},{en:"has",ko:"만든다",t:"verb"},{en:"the crowd",ko:"그 군중을",t:"obj"},{en:"laughing",ko:"웃고 있게",t:"comp"}]},
      {n:32, full:"", chunks:[{en:"I",ko:"나는",t:"subj"},{en:"had",ko:"당했다",t:"verb"},{en:"my leg",ko:"내 다리를",t:"obj"},{en:"broken",ko:"부러지게",t:"comp"}]},
      {n:33, full:"", chunks:[{en:"He",ko:"그는",t:"subj"},{en:"had",ko:"당했다",t:"verb"},{en:"his wallet",ko:"그의 지갑을",t:"obj"},{en:"stolen",ko:"도둑맞게",t:"comp"}]},
      {n:34, full:"", chunks:[{en:"A citizen",ko:"한 시민이",t:"subj"},{en:"feels",ko:"느낀다",t:"verb"},{en:"the water",ko:"그 물이",t:"obj"},{en:"running",ko:"흐르는 것을",t:"comp"},{en:"in the river",ko:"강에서",t:"mod"}]},
      {n:35, full:"", chunks:[{en:"A citizen",ko:"한 시민이",t:"subj"},{en:"notices",ko:"알아차린다",t:"verb"},{en:"the car",ko:"그 차가",t:"obj"},{en:"washed",ko:"씻긴 것을",t:"comp"}]},
      {n:36, full:"", chunks:[{en:"An expert",ko:"한 전문가가",t:"subj"},{en:"sees",ko:"본다",t:"verb"},{en:"the old audience",ko:"그 나이 든 관객이",t:"obj"},{en:"react",ko:"반응하는 것을",t:"comp"}]},
      {n:37, full:"", chunks:[{en:"People",ko:"사람들은",t:"subj"},{en:"feel",ko:"느낀다",t:"verb"},{en:"the rain",ko:"그 비가",t:"obj"},{en:"fall",ko:"떨어지는 것을",t:"comp"},{en:"at the beach",ko:"해변에서",t:"mod"}]},
      {n:38, full:"", chunks:[{en:"Experts",ko:"전문가들은",t:"subj"},{en:"see",ko:"본다",t:"verb"},{en:"the red engine",ko:"그 빨간 엔진이",t:"obj"},{en:"stop",ko:"멈추는 것을",t:"comp"},{en:"on the highway",ko:"고속도로에서",t:"mod"}]},
      {n:39, full:"", chunks:[{en:"A critic",ko:"한 비평가가",t:"subj"},{en:"hears",ko:"듣는다",t:"verb"},{en:"the story",ko:"그 이야기가",t:"obj"},{en:"told",ko:"말해지는 것을",t:"comp"},{en:"in the class",ko:"수업에서",t:"mod"}]},
      {n:40, full:"", chunks:[{en:"A girl",ko:"한 소녀가",t:"subj"},{en:"feels",ko:"느낀다",t:"verb"},{en:"a bug",ko:"벌레 한 마리가",t:"obj"},{en:"moving",ko:"움직이는 것을",t:"comp"},{en:"on her hand",ko:"손 위에서",t:"mod"}]},
      {n:41, full:"", chunks:[{en:"A guest",ko:"한 손님이",t:"subj"},{en:"hears",ko:"듣는다",t:"verb"},{en:"the rain",ko:"그 비가",t:"obj"},{en:"falling",ko:"내리는 것을",t:"comp"}]},
      {n:42, full:"", chunks:[{en:"Experts",ko:"전문가들은",t:"subj"},{en:"watch",ko:"본다",t:"verb"},{en:"the crowd",ko:"그 군중이",t:"obj"},{en:"moving",ko:"움직이는 것을",t:"comp"},{en:"in the area",ko:"그 지역에서",t:"mod"}]},
      {n:43, full:"", chunks:[{en:"People",ko:"사람들은",t:"subj"},{en:"feel",ko:"느낀다",t:"verb"},{en:"the rain",ko:"그 비가",t:"obj"},{en:"falling",ko:"내리는 것을",t:"comp"},{en:"on the highway",ko:"고속도로에서",t:"mod"}]},
      {n:44, full:"", chunks:[{en:"People",ko:"사람들은",t:"subj"},{en:"hear",ko:"듣는다",t:"verb"},{en:"the music",ko:"그 음악이",t:"obj"},{en:"played",ko:"연주되는 것을",t:"comp"}]},
      {n:45, full:"", chunks:[{en:"An expert",ko:"한 전문가가",t:"subj"},{en:"observes",ko:"관찰한다",t:"verb"},{en:"the class",ko:"그 학급이",t:"obj"},{en:"react",ko:"반응하는 것을",t:"comp"}]},
      {n:46, full:"", chunks:[{en:"A parent",ko:"한 부모가",t:"subj"},{en:"hears",ko:"듣는다",t:"verb"},{en:"the crowd",ko:"그 군중이",t:"obj"},{en:"complain",ko:"불평하는 것을",t:"comp"},{en:"by the river",ko:"강가에서",t:"mod"}]},
      {n:47, full:"", chunks:[{en:"Experts",ko:"전문가들은",t:"subj"},{en:"observe",ko:"관찰한다",t:"verb"},{en:"the project",ko:"그 프로젝트가",t:"obj"},{en:"finished",ko:"끝난 것을",t:"comp"}]},
      {n:48, full:"", chunks:[{en:"Experts",ko:"전문가들은",t:"subj"},{en:"notice",ko:"알아차린다",t:"verb"},{en:"the project",ko:"그 프로젝트가",t:"obj"},{en:"finished",ko:"끝난 것을",t:"comp"}]},
      {n:49, full:"", chunks:[{en:"A doctor",ko:"한 의사가",t:"subj"},{en:"observes",ko:"관찰한다",t:"verb"},{en:"the science",ko:"그 과학이",t:"obj"},{en:"understood",ko:"이해되는 것을",t:"comp"},{en:"in the class",ko:"수업에서",t:"mod"}]},
      {n:50, full:"", chunks:[{en:"A critic",ko:"한 비평가가",t:"subj"},{en:"sees",ko:"본다",t:"verb"},{en:"the glass",ko:"그 유리잔이",t:"obj"},{en:"broken",ko:"깨진 것을",t:"comp"}]},
      {n:51, full:"", chunks:[{en:"A doctor",ko:"한 의사가",t:"subj"},{en:"notices",ko:"알아차린다",t:"verb"},{en:"the patient",ko:"그 환자가",t:"obj"},{en:"returning",ko:"돌아오는 것을",t:"comp"}]},
      {n:52, full:"", chunks:[{en:"A citizen",ko:"한 시민이",t:"subj"},{en:"observes",ko:"관찰한다",t:"verb"},{en:"the crowd",ko:"그 군중이",t:"obj"},{en:"reacting",ko:"반응하는 것을",t:"comp"},{en:"in the area",ko:"그 지역에서",t:"mod"}]},
      {n:53, full:"", chunks:[{en:"Doctors",ko:"의사들은",t:"subj"},{en:"see",ko:"본다",t:"verb"},{en:"the patient",ko:"그 환자가",t:"obj"},{en:"returning",ko:"돌아오는 것을",t:"comp"}]},
      {n:54, full:"", chunks:[{en:"Critics",ko:"비평가들은",t:"subj"},{en:"observe",ko:"관찰한다",t:"verb"},{en:"the crowd",ko:"그 군중이",t:"obj"},{en:"cough",ko:"기침하는 것을",t:"comp"}]},
      {n:55, full:"", chunks:[{en:"Parents",ko:"부모들은",t:"subj"},{en:"notice",ko:"알아차린다",t:"verb"},{en:"the crowd",ko:"그 군중이",t:"obj"},{en:"complaining",ko:"불평하는 것을",t:"comp"}]},
      {n:56, full:"", chunks:[{en:"Experts",ko:"전문가들은",t:"subj"},{en:"hear",ko:"듣는다",t:"verb"},{en:"the audience",ko:"그 관객이",t:"obj"},{en:"laughing",ko:"웃고 있는 것을",t:"comp"},{en:"in the forest",ko:"숲에서",t:"mod"}]},
      {n:57, full:"", chunks:[{en:"An expert",ko:"한 전문가가",t:"subj"},{en:"watches",ko:"지켜본다",t:"verb"},{en:"the project",ko:"그 프로젝트가",t:"obj"},{en:"finished",ko:"끝나는 것을",t:"comp"}]},
      {n:58, full:"", chunks:[{en:"An expert",ko:"한 전문가가",t:"subj"},{en:"notices",ko:"알아차린다",t:"verb"},{en:"the proud group",ko:"그 자랑스러운 집단이",t:"obj"},{en:"agree",ko:"동의하는 것을",t:"comp"}]},
      {n:59, full:"", chunks:[{en:"A child",ko:"한 아이가",t:"subj"},{en:"feels",ko:"느낀다",t:"verb"},{en:"the engine",ko:"그 엔진이",t:"obj"},{en:"start",ko:"시작되는 것을",t:"comp"}]},
      {n:60, full:"", chunks:[{en:"People",ko:"사람들은",t:"subj"},{en:"notice",ko:"알아차린다",t:"verb"},{en:"the engine",ko:"그 엔진이",t:"obj"},{en:"stop",ko:"멈추는 것을",t:"comp"},{en:"on the highway",ko:"고속도로에서",t:"mod"}]},
      {n:61, full:"", chunks:[{en:"A critic",ko:"한 비평가가",t:"subj"},{en:"watches",ko:"지켜본다",t:"verb"},{en:"the team",ko:"그 팀이",t:"obj"},{en:"win",ko:"이기는 것을",t:"comp"}]},
      {n:62, full:"", chunks:[{en:"A doctor",ko:"한 의사가",t:"subj"},{en:"sees",ko:"본다",t:"verb"},{en:"the animal",ko:"그 동물이",t:"obj"},{en:"running",ko:"달리는 것을",t:"comp"},{en:"in the desert",ko:"사막에서",t:"mod"}]},
      {n:63, full:"", chunks:[{en:"Citizens",ko:"시민들은",t:"subj"},{en:"feel",ko:"느낀다",t:"verb"},{en:"the engine",ko:"그 엔진이",t:"obj"},{en:"running",ko:"작동하는 것을",t:"comp"}]},
      {n:64, full:"", chunks:[{en:"Parents",ko:"부모들은",t:"subj"},{en:"watch",ko:"본다",t:"verb"},{en:"the rain",ko:"그 비가",t:"obj"},{en:"falling",ko:"내리는 것을",t:"comp"}]},
      {n:65, full:"", chunks:[{en:"Experts",ko:"전문가들은",t:"subj"},{en:"observe",ko:"관찰한다",t:"verb"},{en:"the animal",ko:"그 동물이",t:"obj"},{en:"moving",ko:"움직이는 것을",t:"comp"},{en:"in the forest",ko:"숲에서",t:"mod"}]},
      {n:66, full:"", chunks:[{en:"Experts",ko:"전문가들은",t:"subj"},{en:"see",ko:"본다",t:"verb"},{en:"the issue",ko:"그 문제가",t:"obj"},{en:"understood",ko:"이해되는 것을",t:"comp"}]},
      {n:67, full:"", chunks:[{en:"A child",ko:"한 아이가",t:"subj"},{en:"watches",ko:"지켜본다",t:"verb"},{en:"the animal",ko:"그 동물이",t:"obj"},{en:"run",ko:"달리는 것을",t:"comp"},{en:"in the park",ko:"공원에서",t:"mod"}]},
      {n:68, full:"", chunks:[{en:"People",ko:"사람들은",t:"subj"},{en:"hear",ko:"듣는다",t:"verb"},{en:"the baby",ko:"그 아기가",t:"obj"},{en:"cough",ko:"기침하는 것을",t:"comp"}]},
      {n:69, full:"", chunks:[{en:"Citizens",ko:"시민들은",t:"subj"},{en:"watch",ko:"지켜본다",t:"verb"},{en:"the bridge",ko:"그 다리가",t:"obj"},{en:"built",ko:"지어지는 것을",t:"comp"}]},
      {n:70, full:"", chunks:[{en:"Parents",ko:"부모들은",t:"subj"},{en:"look at",ko:"본다",t:"verb"},{en:"the baby",ko:"그 아기가",t:"obj"},{en:"sleeping",ko:"자고 있는 것을",t:"comp"}]},
      {n:71, full:"", chunks:[{en:"Doctors",ko:"의사들은",t:"subj"},{en:"listen to",ko:"듣는다",t:"verb"},{en:"the audience",ko:"그 관객이",t:"obj"},{en:"laughing",ko:"웃고 있는 것을",t:"comp"}]},
      {n:72, full:"", chunks:[{en:"An expert",ko:"한 전문가가",t:"subj"},{en:"looks at",ko:"본다",t:"verb"},{en:"the team",ko:"그 팀이",t:"obj"},{en:"playing",ko:"경기하는 것을",t:"comp"}]},
      {n:73, full:"", chunks:[{en:"A child",ko:"한 아이가",t:"subj"},{en:"smells",ko:"냄새 맡는다",t:"verb"},{en:"the food",ko:"그 음식이",t:"obj"},{en:"burning",ko:"타는 것을",t:"comp"}]},
      {n:74, full:"", chunks:[{en:"A parent",ko:"한 부모가",t:"subj"},{en:"listens to",ko:"듣는다",t:"verb"},{en:"the child",ko:"그 아이가",t:"obj"},{en:"sing",ko:"노래하는 것을",t:"comp"}]},
      {n:75, full:"", chunks:[{en:"People",ko:"사람들은",t:"subj"},{en:"smell",ko:"냄새 맡는다",t:"verb"},{en:"the engine",ko:"그 엔진이",t:"obj"},{en:"burn",ko:"타는 것을",t:"comp"}]},
    ]},
  ],
  vocab:[
    { id:"5형식(1)", items:[
      {en:"believe", ko:["믿다"], pos:"v"},
      {en:"keep", ko:["유지하다"], pos:"v"},
      {en:"familiar", ko:["익숙한"], pos:"adj"},
      {en:"honest", ko:["정직한"], pos:"adj"},
      {en:"warm", ko:["따뜻한"], pos:"adj"},
      {en:"leader", ko:["지도자"], pos:"n"},
      {en:"adult", ko:["성인"], pos:"n"},
      {en:"engine", ko:["엔진"], pos:"n"},
      {en:"kitchen", ko:["부엌"], pos:"n"},
      {en:"member", ko:["구성원"], pos:"n"},
      {en:"movie", ko:["영화"], pos:"n"},
      {en:"opinion", ko:["의견"], pos:"n"},
      {en:"parent", ko:["부모"], pos:"n"},
      {en:"people", ko:["사람들"], pos:"n"},
      {en:"research", ko:["연구"], pos:"n"},
      {en:"star", ko:["별","스타"], pos:"n"},
      {en:"success", ko:["성공"], pos:"n"},
      {en:"table", ko:["탁자"], pos:"n"},
      {en:"victim", ko:["피해자"], pos:"n"},
      {en:"water", ko:["물"], pos:"n"},
      {en:"call", ko:["부르다","~라고 부르다"], pos:"v"},
      {en:"name", ko:["이름","~라고 명명하다"], pos:"v"},
      {en:"leave", ko:["떠나다","~한 채로 두다"], pos:"v"},
      {en:"elect", ko:["선출하다"], pos:"v"},
      {en:"president", ko:["회장","대통령"], pos:"n"},
      {en:"captain", ko:["주장","선장"], pos:"n"},
      {en:"readmical", ko:["(고유명사) 수업명"], pos:"n"},
    ]},
    { id:"5형식(2)", items:[
      {en:"agree", ko:["동의하다"], pos:"v"},
      {en:"complain", ko:["불평하다"], pos:"v"},
      {en:"cough", ko:["기침하다"], pos:"v"},
      {en:"help", ko:["돕다"], pos:"v"},
      {en:"laugh", ko:["웃다"], pos:"v"},
      {en:"play", ko:["놀다","연주하다"], pos:"v"},
      {en:"react", ko:["반응하다"], pos:"v"},
      {en:"return", ko:["돌아오다"], pos:"v"},
      {en:"stop", ko:["멈추다"], pos:"v"},
      {en:"succeed", ko:["성공하다"], pos:"v"},
      {en:"understand", ko:["이해하다"], pos:"v"},
      {en:"win", ko:["이기다"], pos:"v"},
      {en:"decide", ko:["결정하다"], pos:"v"},
      {en:"start", ko:["시작하다"], pos:"v"},
      {en:"animal", ko:["동물"], pos:"n"},
      {en:"area", ko:["지역"], pos:"n"},
      {en:"audience", ko:["관객"], pos:"n"},
      {en:"baby", ko:["아기"], pos:"n"},
      {en:"beach", ko:["해변"], pos:"n"},
      {en:"class", ko:["수업","학급"], pos:"n"},
      {en:"crowd", ko:["군중"], pos:"n"},
      {en:"desert", ko:["사막"], pos:"n"},
      {en:"family", ko:["가족"], pos:"n"},
      {en:"floor", ko:["바닥"], pos:"n"},
      {en:"glass", ko:["유리","잔"], pos:"n"},
      {en:"group", ko:["집단"], pos:"n"},
      {en:"highway", ko:["고속도로"], pos:"n"},
      {en:"hour", ko:["시간"], pos:"n"},
      {en:"issue", ko:["문제","사안"], pos:"n"},
      {en:"lady", ko:["숙녀"], pos:"n"},
      {en:"music", ko:["음악"], pos:"n"},
      {en:"park", ko:["공원"], pos:"n"},
      {en:"project", ko:["프로젝트"], pos:"n"},
      {en:"rain", ko:["비"], pos:"n"},
      {en:"science", ko:["과학"], pos:"n"},
      {en:"old", ko:["오래된","늙은"], pos:"adj"},
      {en:"proud", ko:["자랑스러운"], pos:"adj"},
      {en:"watch", ko:["보다","시계"], pos:"v"},
      {en:"have", ko:["가지다","~하게 시키다"], pos:"v"},
      {en:"let", ko:["~하게 두다"], pos:"v"},
      {en:"see", ko:["보다"], pos:"v"},
      {en:"hear", ko:["듣다"], pos:"v"},
      {en:"notice", ko:["알아차리다"], pos:"v"},
      {en:"observe", ko:["관찰하다"], pos:"v"},
      {en:"bug", ko:["벌레"], pos:"n"},
      {en:"look at", ko:["~을 보다"], pos:"v"},
      {en:"listen to", ko:["~을 듣다"], pos:"v"},
      {en:"smell", ko:["~의 냄새를 맡다"], pos:"v"},
      {en:"burn", ko:["(불에) 타다"], pos:"v"},
      {en:"leg", ko:["다리"], pos:"n"},
      {en:"wallet", ko:["지갑"], pos:"n"},
      {en:"steal", ko:["훔치다"], pos:"v"},
    ]},
  ]
};
